<template>
  <div
    class="
      bg-white
      shadow-lg
      rounded-lg
      p-4
      flex flex-col
      col-span-1
      dark:bg-dark-1
      relative
    "
  >
    <div class="absolute inset-0 z-10 bg-transparent">
      <div
        class="
          flex
          justify-center
          items-center
          h-full
          text-lg
          font-bold
          text-center
          dark:text-white
          mx-4
        "
      ></div>
    </div>
    <h3
      class="
        text-lg
        flex
        justify-between
        items-center
        text-gray-500
        dark:text-gray-400
        filter
        blur-sm
      "
    >
      Receive
    </h3>
    <div
      class="flex flex-col justify-center items-center flex-grow filter blur-sm"
    >
      <span
        class="
          w-10/12
          text-sm text-center
          break-words
          hover:text-blue-500
          transition
          duration-300
          cursor-pointer
          dark:text-white
        "
        >0x78665f6d14727401cb7ea58ef23fd5350270f365</span
      >
      <div class="flex justify-center bg-white shadow-xl p-2 rounded-xl mt-4">
        <img src="/qrcode.png" alt="" />
      </div>
      <button
        class="
          mt-6
          bg-white
          dark:bg-nice-dark
          text-black
          dark:text-white
          border-2 border-black
          dark:border-white
          px-5
          py-2
          text-sm
          rounded-lg
          transition
          duration-300
          ring-offset-2
          hover:text-white
          dark:hover:text-black
          hover:border-black
          dark:hover:border-white
          hover:bg-black
          dark:hover:bg-white
          focus:text-white
          dark:focus:text-black
          focus:bg-black
          dark:focus:bg-white
          focus:border-black
          dark:focus:border-white
          focus:ring focus:ring-black
          dark:focus:ring-white
          focus:outline-none
          dark:ring-offset-black
        "
      >
        Partager <i class="bx bxs-share-alt ml-2"></i>
      </button>
    </div>
  </div>
</template>
